{
  if (_uncaughtExceptionHandler != null) {
    _uncaughtExceptionHandler.uncaughtException(thread,throwable);
  }
  StringBundler sb=new StringBundler(4);
  sb.append("Uncaught exception in ");
  sb.append(thread);
  sb.append(StringPool.COMMA_AND_SPACE);
  sb.append(throwable);
  LogAssertionTestCallback.caughtFailure(new AssertionError(sb.toString(),throwable));
}
