{
  try {
    return super.get();
  }
 catch (  ExecutionException ee) {
    throw new AssertionError("Not possible to throw ExecutionException",ee);
  }
}
