{
  try {
    return MethodInvoker.invoke(_methodWrapper,object);
  }
 catch (  InvocationTargetException e) {
    Throwable targetThrowable=e.getCause();
    if (targetThrowable instanceof Exception) {
      throw (Exception)targetThrowable;
    }
 else {
      throw new Exception(targetThrowable);
    }
  }
}
