{
  try {
    addTrackback(actionRequest,actionResponse);
  }
 catch (  Exception e) {
    sendError(actionResponse,"An unknown error has occurred.");
    _log.error(e);
  }
  setForward(actionRequest,ActionConstants.COMMON_NULL);
}
