{
  try {
    _persistence.countByScope(RandomTestUtil.nextInt());
    _persistence.countByScope(0);
  }
 catch (  Exception e) {
    Assert.fail(e.getMessage());
  }
}
